### Spring
spring.application.name=geo

# Cache
spring.cache.cache-names=location
spring.cache.caffeine.spec=maximumSize=100, expireAfterAccess=10m

# Cors
spring.cors.allow-credentials=true
spring.cors.allowed-methods=GET, POST, OPTIONS
spring.cors.allowed-origins=

### App
# Settings
app.location.detector=ipstack

# Integrations
app.integrations.ipstack.url=
app.integrations.ipstack.accessKey=
